
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 2;
  public static final int LBRACKET = 15;
  public static final int PERIOD = 9;
  public static final int LPAREN = 11;
  public static final int INT = 21;
  public static final int MINUS = 4;
  public static final int STATIC = 28;
  public static final int RPAREN = 12;
  public static final int SOUT = 35;
  public static final int NOT = 8;
  public static final int SEMICOLON = 13;
  public static final int AND = 6;
  public static final int COMMA = 14;
  public static final int CLASS = 26;
  public static final int PLUS = 3;
  public static final int MAIN = 30;
  public static final int IF = 32;
  public static final int THIS = 36;
  public static final int EOF = 0;
  public static final int BOOLEAN = 22;
  public static final int RETURN = 37;
  public static final int RBRACKET = 16;
  public static final int TRUE = 24;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int BECOMES = 7;
  public static final int VOID = 29;
  public static final int TIMES = 5;
  public static final int LBRACE = 17;
  public static final int ELSE = 33;
  public static final int LETTER = 20;
  public static final int WHILE = 34;
  public static final int PUBLIC = 27;
  public static final int RBRACE = 18;
  public static final int EXTENDS = 38;
  public static final int STRING = 40;
  public static final int FALSE = 25;
  public static final int LESS_THAN = 10;
  public static final int LENGTH = 39;
  public static final int INTEGER_LITERAL = 23;
  public static final int IDENTIFIER = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DISPLAY",
  "PLUS",
  "MINUS",
  "TIMES",
  "AND",
  "BECOMES",
  "NOT",
  "PERIOD",
  "LESS_THAN",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "COMMA",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "IDENTIFIER",
  "LETTER",
  "INT",
  "BOOLEAN",
  "INTEGER_LITERAL",
  "TRUE",
  "FALSE",
  "CLASS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "NEW",
  "IF",
  "ELSE",
  "WHILE",
  "SOUT",
  "THIS",
  "RETURN",
  "EXTENDS",
  "LENGTH",
  "STRING"
  };
}

